# Generated by Django 5.1.5 on 2025-08-10 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='verification_expires_at',
        ),
        migrations.CreateModel(
            name='SnowShoveling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('note', models.TextField(blank=True, null=True)),
                ('cabin_number', models.IntegerField()),
                ('person_ordered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snow_shoveling_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
